export type ComponentStatus = "planned" | "draft" | "ready" | "stable";

export interface ComponentCategory {
  id: string;
  label: string;
  description: string;
}

export interface ComponentCatalogItem {
  name: string;
  slug: string;
  category: string;
  priority: "P0" | "P1" | "P2";
  status: ComponentStatus;
  summary: string;
  purpose: string;
  primitive: string;
  apg: string;
  props: string[];
  states: string[];
  tokens: string[];
}

export const componentStatuses: Record<ComponentStatus, string> = {
  planned: "폴더, README, spec이 있고 구현은 아직 시작하지 않은 상태입니다.",
  draft: "정적 API와 접근성 계약이 문서화되어 구현을 시작할 수 있는 상태입니다.",
  ready: "구현, 예시, 핵심 접근성 확인이 완료된 상태입니다.",
  stable: "문서 앱에서 사용되고 API 검토와 회귀 테스트가 충분한 상태입니다."
};

export const componentCategories: ComponentCategory[] = [
  {
    id: "actions",
    label: "액션",
    description: "명시적인 사용자 명령을 실행합니다."
  },
  {
    id: "forms",
    label: "폼",
    description: "사용자 입력을 수집하고 검증하며 제출 흐름에 연결합니다."
  },
  {
    id: "feedback",
    label: "피드백",
    description: "상태, 진행 상황, 시스템 결과를 전달합니다."
  },
  {
    id: "overlays",
    label: "오버레이",
    description: "현재 화면 위에 맥락형 또는 차단형 UI 계층을 만듭니다."
  },
  {
    id: "navigation",
    label: "내비게이션",
    description: "위치, 섹션, 관련 panel 사이를 이동합니다."
  },
  {
    id: "layout",
    label: "레이아웃",
    description: "콘텐츠와 반복 product surface의 구조를 만듭니다."
  },
  {
    id: "data-display",
    label: "데이터 표시",
    description: "collection, record, empty state, tabular data를 보여줍니다."
  }
];

export const componentCatalog: ComponentCatalogItem[] = [
  {
    name: "Button",
    slug: "button",
    category: "actions",
    priority: "P0",
    status: "ready",
    summary: "명시적인 사용자 행동을 실행하는 기본 명령 컨트롤입니다.",
    purpose: "폼 제출, 확인, 취소, 삭제처럼 사용자가 의도를 확정하는 작업에 사용합니다.",
    primitive: "button",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/button/",
    props: ["variant", "tone", "size", "disabled", "loading", "type", "fullWidth", "selected", "justify", "iconStart", "iconEnd"],
    states: ["default", "hover", "focus-visible", "active", "disabled", "loading", "selected"],
    tokens: ["--ds-color-action-primary-bg", "--ds-radius-6", "--ds-focus-ring"]
  },
  {
    name: "IconButton",
    slug: "icon-button",
    category: "actions",
    priority: "P0",
    status: "ready",
    summary: "accessible name이 필수인 compact icon-only action입니다.",
    purpose: "공간이 좁고 익숙한 아이콘으로 행동을 표현할 수 있을 때 사용합니다.",
    primitive: "button",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/button/",
    props: ["label", "icon", "variant", "tone", "size", "shape", "disabled", "loading"],
    states: ["default", "hover", "focus-visible", "active", "disabled", "loading"],
    tokens: ["--ds-color-action-primary-bg", "--ds-radius-6", "--ds-focus-ring"]
  },
  {
    name: "Icon",
    slug: "icon",
    category: "actions",
    priority: "P1",
    status: "ready",
    summary: "토큰 기반 크기와 접근성 기본값을 가진 공용 SVG symbol renderer입니다.",
    purpose: "반복되는 product symbol을 외부 icon library 도입 전후로 일관되게 유지할 때 사용합니다.",
    primitive: "svg",
    apg: "https://www.w3.org/WAI/tutorials/images/decision-tree/",
    props: ["name", "label", "size"],
    states: ["decorative", "informative", "inherited-color"],
    tokens: ["--ds-size-icon-sm", "--ds-size-icon-md", "--ds-size-icon-lg"]
  },
  {
    name: "Link",
    slug: "link",
    category: "actions",
    priority: "P1",
    status: "ready",
    summary: "실제 위치 이동을 담당하는 native anchor 기반 컴포넌트입니다.",
    purpose: "페이지, 문서, 외부 주소처럼 사용자가 다른 위치로 이동해야 할 때 사용합니다.",
    primitive: "a",
    apg: "https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element",
    props: ["href", "children", "label", "variant", "tone", "size", "iconStart", "iconEnd", "external", "externalLabel", "disabled"],
    states: ["default", "hover", "focus-visible", "external", "disabled"],
    tokens: ["--ds-color-action-primary-bg", "--ds-color-text-primary", "--ds-focus-ring"]
  },
  {
    name: "Field",
    slug: "field",
    category: "forms",
    priority: "P0",
    status: "ready",
    summary: "form control의 label, description, error, required marker를 공유하는 wrapper입니다.",
    purpose: "폼 copy, validation feedback, accessible relationship을 표준화할 때 사용합니다.",
    primitive: "label and form control relationship",
    apg: "https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/",
    props: ["label", "description", "error", "required", "disabled", "controlId", "orientation", "width", "hideLabel"],
    states: ["default", "disabled", "invalid", "required"],
    tokens: ["--ds-color-text-primary", "--ds-color-text-muted", "--ds-color-feedback-danger"]
  },
  {
    name: "TextField",
    slug: "text-field",
    category: "forms",
    priority: "P0",
    status: "ready",
    summary: "Field composition과 함께 쓰는 single-line text input입니다.",
    purpose: "이름, 짧은 설명, URL, email, 검색어처럼 한 줄 text value를 입력할 때 사용합니다.",
    primitive: "input",
    apg: "https://html.spec.whatwg.org/multipage/input.html",
    props: ["value", "defaultValue", "placeholder", "type", "size", "width", "prefix", "suffix", "fieldProps", "inputClassName", "disabled", "readOnly", "invalid"],
    states: ["default", "hover", "focus-visible", "disabled", "read-only", "invalid"],
    tokens: ["--ds-color-bg-surface", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "SearchField",
    slug: "search-field",
    category: "forms",
    priority: "P1",
    status: "ready",
    summary: "검색 입력과 clear 동작을 표준화한 단일 행 검색 필드입니다.",
    purpose: "목록, 테이블, 명령 영역에서 검색어를 입력하고 결과 영역과 연결해야 할 때 사용합니다.",
    primitive: "input[type='search']",
    apg: "https://html.spec.whatwg.org/multipage/input.html#text-(type=text)-state-and-search-state-(type=search)",
    props: ["label", "description", "error", "value", "defaultValue", "onValueChange", "onClear", "placeholder", "size", "width", "fieldProps", "inputClassName", "resultsId", "clearLabel", "disabled", "required"],
    states: ["empty", "filled", "focus-visible", "disabled", "invalid"],
    tokens: ["--ds-color-bg-surface", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "Textarea",
    slug: "textarea",
    category: "forms",
    priority: "P1",
    status: "ready",
    summary: "Field composition과 함께 쓰는 multi-line text entry입니다.",
    purpose: "긴 자유 입력, comment, description, note를 받을 때 사용합니다.",
    primitive: "textarea",
    apg: "https://html.spec.whatwg.org/multipage/form-elements.html#the-textarea-element",
    props: ["value", "defaultValue", "placeholder", "rows", "resize", "size", "width", "fieldProps", "textareaClassName", "disabled", "readOnly", "invalid"],
    states: ["default", "hover", "focus-visible", "disabled", "read-only", "invalid"],
    tokens: ["--ds-color-bg-surface", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "Select",
    slug: "select",
    category: "forms",
    priority: "P0",
    status: "ready",
    summary: "알려진 선택지 집합에서 하나의 option을 선택하는 control입니다.",
    purpose: "제한된 선택지를 하나 고를 때 사용하며, 검색이나 rich option이 필요할 때만 custom listbox나 combobox로 확장합니다.",
    primitive: "select or combobox/listbox pattern",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/combobox/",
    props: ["value", "defaultValue", "options", "placeholder", "size", "width", "prefix", "suffix", "fieldProps", "selectClassName", "disabled", "invalid"],
    states: ["default", "hover", "focus-visible", "open", "disabled", "invalid"],
    tokens: ["--ds-color-bg-surface", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "DatePicker",
    slug: "date-picker",
    category: "forms",
    priority: "P0",
    status: "ready",
    summary: "Field composition을 공유하는 날짜 입력입니다.",
    purpose: "workflow에 단일 calendar date가 필요하고 native browser behavior를 우선할 때 사용합니다.",
    primitive: "input[type='date']",
    apg: "https://html.spec.whatwg.org/multipage/input.html#date-state-(type=date)",
    props: ["value", "defaultValue", "minDate", "maxDate", "size", "width", "fieldProps", "inputClassName", "disabled", "readOnly", "invalid"],
    states: ["default", "hover", "focus-visible", "disabled", "read-only", "invalid"],
    tokens: ["--ds-color-bg-surface", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "Combobox",
    slug: "combobox",
    category: "forms",
    priority: "P0",
    status: "ready",
    summary: "알려진 option set에서 검색 가능한 단일 값을 선택합니다.",
    purpose: "select에 filtering, text input, 많은 option 처리가 필요하지만 현재 form을 벗어나지 않아야 할 때 사용합니다.",
    primitive: "combobox with listbox popup",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/combobox/",
    props: ["label", "description", "error", "value", "defaultValue", "options", "placeholder", "emptyMessage", "size", "width", "disabled", "required", "fieldProps", "onValueChange"],
    states: ["closed", "open", "filtered", "highlighted", "selected", "disabled", "invalid"],
    tokens: ["--ds-color-bg-surface", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "Checkbox",
    slug: "checkbox",
    category: "forms",
    priority: "P0",
    status: "ready",
    summary: "binary 또는 mixed-state option control입니다.",
    purpose: "독립 choice, agreement, multi-select list에 사용합니다.",
    primitive: "input[type='checkbox']",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/",
    props: ["checked", "defaultChecked", "indeterminate", "disabled", "invalid"],
    states: ["unchecked", "checked", "indeterminate", "focus-visible", "disabled", "invalid"],
    tokens: ["--ds-color-action-primary-bg", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "RadioGroup",
    slug: "radio-group",
    category: "forms",
    priority: "P0",
    status: "ready",
    summary: "visible option set에서 상호 배타적으로 하나를 선택하는 control입니다.",
    purpose: "모든 선택지를 계속 보여줘야 하고 하나의 값만 선택할 수 있을 때 사용합니다.",
    primitive: "fieldset with input[type='radio']",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/radio/",
    props: ["value", "defaultValue", "options", "orientation", "disabled", "invalid"],
    states: ["unchecked", "checked", "focus-visible", "disabled", "invalid"],
    tokens: ["--ds-color-action-primary-bg", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "Switch",
    slug: "switch",
    category: "forms",
    priority: "P0",
    status: "ready",
    summary: "즉시 반영되는 on/off setting control입니다.",
    purpose: "form submission이 아니라 즉시 적용되는 설정에 사용합니다.",
    primitive: "button or input checkbox with switch semantics",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/switch/",
    props: ["checked", "defaultChecked", "disabled", "label", "onCheckedChange"],
    states: ["off", "on", "focus-visible", "disabled"],
    tokens: ["--ds-color-action-primary-bg", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "FileUploader",
    slug: "file-uploader",
    category: "forms",
    priority: "P1",
    status: "ready",
    summary: "파일 선택 상태와 metadata를 보여주는 file selection control입니다.",
    purpose: "사용자가 하나 이상의 파일을 첨부하면서 제약과 선택된 파일을 확인해야 할 때 사용합니다.",
    primitive: "input[type='file']",
    apg: "https://html.spec.whatwg.org/multipage/input.html#file-upload-state-(type=file)",
    props: ["label", "description", "helperText", "accept", "multiple", "files", "defaultFiles", "maxFiles", "disabled", "error", "onFilesChange"],
    states: ["default", "hover", "focus-visible", "drag-over", "disabled", "invalid"],
    tokens: ["--ds-color-bg-surface", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "Alert",
    slug: "alert",
    category: "feedback",
    priority: "P0",
    status: "ready",
    summary: "중요한 contextual feedback을 보여주는 inline status message입니다.",
    purpose: "흐름을 막지 않는 정보, 성공, 경고, 오류 메시지에 사용합니다.",
    primitive: "role='status' or role='alert'",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/alert/",
    props: ["tone", "title", "description", "icon", "actions", "variant", "actionsPlacement", "dismissible", "dismissLabel", "onDismiss"],
    states: ["info", "success", "warning", "danger", "dismissible"],
    tokens: ["--ds-color-feedback-success", "--ds-color-feedback-warning", "--ds-color-feedback-danger"]
  },
  {
    name: "Toast",
    slug: "toast",
    category: "feedback",
    priority: "P1",
    status: "ready",
    summary: "짧게 표시되는 global notification입니다.",
    purpose: "workflow를 방해하지 않아야 하는 짧은 결과 알림에 사용합니다.",
    primitive: "status region with dismiss control",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/alert/",
    props: ["tone", "title", "description", "duration", "dismissible", "dismissLabel", "actions", "onDismiss"],
    states: ["entering", "open", "exiting", "dismissed"],
    tokens: ["--ds-z-toast", "--ds-shadow-raised", "--ds-motion-duration-normal"]
  },
  {
    name: "Badge",
    slug: "badge",
    category: "feedback",
    priority: "P0",
    status: "ready",
    summary: "작은 status 또는 metadata label입니다.",
    purpose: "dense interface에서 status, category, count, short metadata를 표시할 때 사용합니다.",
    primitive: "span",
    apg: "",
    props: ["tone", "variant", "size", "iconStart", "iconEnd", "removable", "removeLabel", "onRemove"],
    states: ["neutral", "info", "success", "warning", "danger", "removable"],
    tokens: ["--ds-radius-pill", "--ds-color-bg-muted", "--ds-color-text-muted"]
  },
  {
    name: "Progress",
    slug: "progress",
    category: "feedback",
    priority: "P1",
    status: "ready",
    summary: "determinate 또는 indeterminate task progress를 표시합니다.",
    purpose: "사용자가 task completion이나 waiting state를 이해해야 할 때 사용합니다.",
    primitive: "progress",
    apg: "",
    props: ["value", "max", "label", "indeterminate", "tone"],
    states: ["determinate", "indeterminate", "complete"],
    tokens: ["--ds-color-action-primary-bg", "--ds-color-bg-muted", "--ds-motion-duration-normal"]
  },
  {
    name: "Spinner",
    slug: "spinner",
    category: "feedback",
    priority: "P1",
    status: "ready",
    summary: "짧은 대기 상태를 보여주는 원형 진행 표시입니다.",
    purpose: "레이아웃을 유지할 필요는 작고, 사용자가 짧은 비동기 대기 상태만 알아야 할 때 사용합니다.",
    primitive: "status span or decorative span",
    apg: "https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/",
    props: ["size", "tone", "label", "status"],
    states: ["status", "decorative", "animated"],
    tokens: ["--ds-size-icon-sm", "--ds-size-icon-md", "--ds-size-icon-lg", "--ds-motion-duration-normal"]
  },
  {
    name: "InlineLoading",
    slug: "inline-loading",
    category: "feedback",
    priority: "P1",
    status: "ready",
    summary: "스피너와 텍스트를 함께 보여주는 인라인 상태 표시입니다.",
    purpose: "버튼 밖의 짧은 대기, 저장 중, 동기화 결과처럼 텍스트 상태를 함께 전달해야 할 때 사용합니다.",
    primitive: "role='status'",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/alert/",
    props: ["label", "description", "size", "tone", "status"],
    states: ["loading", "success", "error"],
    tokens: ["--ds-color-text-primary", "--ds-color-text-muted", "--ds-motion-duration-normal"]
  },
  {
    name: "Skeleton",
    slug: "skeleton",
    category: "feedback",
    priority: "P1",
    status: "ready",
    summary: "loading content를 대신하는 placeholder surface입니다.",
    purpose: "비동기 content가 loading되는 동안 layout을 유지할 때 사용합니다.",
    primitive: "div with aria-hidden when decorative",
    apg: "",
    props: ["shape", "width", "height", "animated"],
    states: ["static", "animated"],
    tokens: ["--ds-color-bg-muted", "--ds-motion-duration-normal", "--ds-radius-6"]
  },
  {
    name: "Dialog",
    slug: "dialog",
    category: "overlays",
    priority: "P1",
    status: "ready",
    summary: "사용자의 집중이 필요한 modal surface입니다.",
    purpose: "확인, 짧은 form, 돌아가기 전에 끝내야 하는 task에 사용합니다.",
    primitive: "dialog or modal dialog pattern",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/",
    props: ["open", "defaultOpen", "onOpenChange", "modal", "size", "initialFocus", "closeLabel", "closeOnBackdropClick"],
    states: ["closed", "opening", "open", "closing"],
    tokens: ["--ds-z-dialog", "--ds-shadow-raised", "--ds-radius-8"]
  },
  {
    name: "Popover",
    slug: "popover",
    category: "overlays",
    priority: "P1",
    status: "ready",
    summary: "non-modal contextual floating surface입니다.",
    purpose: "trigger에 연결된 contextual detail, filter, lightweight control에 사용합니다.",
    primitive: "button plus positioned region",
    apg: "",
    props: ["open", "defaultOpen", "onOpenChange", "placement"],
    states: ["closed", "opening", "open", "closing"],
    tokens: ["--ds-z-popover", "--ds-shadow-raised", "--ds-radius-8"]
  },
  {
    name: "Tooltip",
    slug: "tooltip",
    category: "overlays",
    priority: "P1",
    status: "ready",
    summary: "focus 또는 hover된 control을 위한 짧은 helper text입니다.",
    purpose: "visible label을 대체하지 않고 icon-only 또는 compact control을 보조 설명할 때 사용합니다.",
    primitive: "tooltip pattern",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/",
    props: ["content", "placement", "delay", "disabled"],
    states: ["closed", "delayed-open", "open"],
    tokens: ["--ds-z-popover", "--ds-color-gray-900", "--ds-radius-4"]
  },
  {
    name: "DropdownMenu",
    slug: "dropdown-menu",
    category: "overlays",
    priority: "P1",
    status: "ready",
    summary: "trigger에서 열리는 action menu입니다.",
    purpose: "contextual command, overflow action, compact action group에 사용합니다.",
    primitive: "menu button pattern",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/",
    props: ["open", "defaultOpen", "items", "placement", "onOpenChange"],
    states: ["closed", "open", "highlighted", "disabled"],
    tokens: ["--ds-z-dropdown", "--ds-shadow-raised", "--ds-radius-6"]
  },
  {
    name: "CommandPalette",
    slug: "command-palette",
    category: "overlays",
    priority: "P1",
    status: "ready",
    summary: "keyboard 친화적인 command search surface입니다.",
    purpose: "global command discovery, quick navigation, shortcut-driven action에 사용합니다.",
    primitive: "dialog with combobox-style command list",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/",
    props: ["title", "triggerLabel", "commands", "open", "defaultOpen", "placeholder", "emptyMessage", "onOpenChange", "onCommandSelect"],
    states: ["closed", "open", "filtered", "highlighted", "empty"],
    tokens: ["--ds-z-dialog", "--ds-shadow-raised", "--ds-focus-ring"]
  },
  {
    name: "Tabs",
    slug: "tabs",
    category: "navigation",
    priority: "P0",
    status: "ready",
    summary: "같은 context 안에서 관련 panel을 전환합니다.",
    purpose: "같은 page location을 공유하는 peer section을 full navigation 없이 전환할 때 사용합니다.",
    primitive: "tabs pattern",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/tabs/",
    props: ["value", "defaultValue", "orientation", "activationMode", "variant", "size", "fullWidth", "keepMounted", "disabled"],
    states: ["selected", "unselected", "focus-visible", "disabled"],
    tokens: ["--ds-color-action-primary-bg", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "Breadcrumb",
    slug: "breadcrumb",
    category: "navigation",
    priority: "P1",
    status: "ready",
    summary: "계층형 page location trail입니다.",
    purpose: "상위 location을 보여주고 빠른 상위 이동을 지원할 때 사용합니다.",
    primitive: "nav with ordered list",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/breadcrumb/",
    props: ["items", "separator", "maxItems"],
    states: ["current", "link"],
    tokens: ["--ds-color-text-muted", "--ds-color-action-primary-bg"]
  },
  {
    name: "Pagination",
    slug: "pagination",
    category: "navigation",
    priority: "P1",
    status: "ready",
    summary: "paged collection을 이동하는 navigation control입니다.",
    purpose: "dataset이 page로 나뉘고 직접 또는 순차 navigation이 필요할 때 사용합니다.",
    primitive: "nav with links or buttons",
    apg: "",
    props: ["page", "defaultPage", "totalPages", "siblingCount", "disabled", "onPageChange"],
    states: ["current", "available", "disabled"],
    tokens: ["--ds-color-border-default", "--ds-color-action-primary-bg", "--ds-focus-ring"]
  },
  {
    name: "Stepper",
    slug: "stepper",
    category: "navigation",
    priority: "P1",
    status: "ready",
    summary: "순서가 있는 workflow 진행 상태와 step navigation을 보여줍니다.",
    purpose: "multi-step flow에서 현재 진행 상태와 선택적 step 이동이 필요할 때 사용합니다.",
    primitive: "ordered list navigation",
    apg: "",
    props: ["steps", "value", "defaultValue", "orientation", "variant", "onValueChange"],
    states: ["pending", "active", "complete", "keyboard-navigation", "disabled", "error"],
    tokens: ["--ds-color-border-default", "--ds-color-action-primary-bg", "--ds-focus-ring"]
  },
  {
    name: "NavigationRail",
    slug: "navigation-rail",
    category: "navigation",
    priority: "P1",
    status: "ready",
    summary: "app shell을 위한 compact vertical primary navigation입니다.",
    purpose: "wide layout에서 top-level destination을 persistent icon-first navigation으로 보여줄 때 사용합니다.",
    primitive: "nav with list of links or buttons",
    apg: "",
    props: ["items", "value", "defaultValue", "label", "collapsed", "onValueChange"],
    states: ["default", "selected", "disabled", "collapsed"],
    tokens: ["--ds-color-bg-surface", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "SideNav",
    slug: "side-nav",
    category: "navigation",
    priority: "P1",
    status: "ready",
    summary: "product workspace를 위한 sectioned vertical navigation입니다.",
    purpose: "grouped destination과 persistent current state가 필요한 application sidebar에 사용합니다.",
    primitive: "nav with grouped lists",
    apg: "",
    props: ["sections", "value", "defaultValue", "label", "collapsible", "collapsed", "onValueChange"],
    states: ["expanded", "collapsed", "selected", "disabled"],
    tokens: ["--ds-color-bg-surface", "--ds-color-border-default", "--ds-focus-ring"]
  },
  {
    name: "Container",
    slug: "container",
    category: "layout",
    priority: "P0",
    status: "ready",
    summary: "product layout의 responsive page-width wrapper입니다.",
    purpose: "page content를 예측 가능한 readable width로 제한하면서 safe gutter를 유지할 때 사용합니다.",
    primitive: "div",
    apg: "",
    props: ["size"],
    states: ["sm", "md", "lg", "xl", "2xl"],
    tokens: ["--ds-container-sm", "--ds-container-md", "--ds-container-lg", "--ds-page-gutter"]
  },
  {
    name: "Row",
    slug: "row",
    category: "layout",
    priority: "P0",
    status: "ready",
    summary: "공유 gap, alignment, justification 축을 가진 horizontal flex layout primitive입니다.",
    purpose: "관련 children을 wrapping horizontal flow로 배치할 때 사용합니다.",
    primitive: "div",
    apg: "",
    props: ["gap", "align", "justify"],
    states: ["gap-sm", "gap-md", "gap-lg", "aligned", "justified"],
    tokens: ["--ds-layout-gap-sm", "--ds-layout-gap-md", "--ds-layout-gap-lg"]
  },
  {
    name: "Col",
    slug: "col",
    category: "layout",
    priority: "P0",
    status: "ready",
    summary: "Row layout 안에서 쓰는 responsive 12-column child primitive입니다.",
    purpose: "viewport breakpoint에 따라 column span을 정의할 때 사용합니다.",
    primitive: "div",
    apg: "",
    props: ["span", "sm", "md", "lg"],
    states: ["span", "sm", "md", "lg"],
    tokens: ["--ds-breakpoint-sm", "--ds-breakpoint-md", "--ds-breakpoint-lg"]
  },
  {
    name: "Stack",
    slug: "stack",
    category: "layout",
    priority: "P0",
    status: "ready",
    summary: "공유 gap과 alignment 축을 가진 vertical layout primitive입니다.",
    purpose: "form field, action, repeated block을 예측 가능한 spacing으로 쌓을 때 사용합니다.",
    primitive: "div",
    apg: "",
    props: ["gap", "align"],
    states: ["gap-sm", "gap-md", "gap-lg", "aligned"],
    tokens: ["--ds-layout-gap-sm", "--ds-layout-gap-md", "--ds-layout-gap-lg"]
  },
  {
    name: "Inline",
    slug: "inline",
    category: "layout",
    priority: "P0",
    status: "ready",
    summary: "compact group을 위한 inline wrapping layout primitive입니다.",
    purpose: "badge, action, filter, short metadata를 wrapping inline flow로 정렬할 때 사용합니다.",
    primitive: "div",
    apg: "",
    props: ["gap", "align", "justify"],
    states: ["gap-sm", "gap-md", "gap-lg", "aligned", "justified"],
    tokens: ["--ds-layout-gap-sm", "--ds-layout-gap-md", "--ds-layout-gap-lg"]
  },
  {
    name: "Card",
    slug: "card",
    category: "layout",
    priority: "P0",
    status: "ready",
    summary: "관련 content와 action을 묶는 surface입니다.",
    purpose: "반복 record, summary panel, 독립 content group에 사용합니다.",
    primitive: "article or section",
    apg: "",
    props: ["title", "eyebrow", "description", "media", "meta", "actions", "footer", "variant", "density", "interactive", "selected", "fullWidth", "actionPlacement"],
    states: ["default", "hover", "focus-visible", "selected"],
    tokens: ["--ds-color-bg-surface", "--ds-color-border-default", "--ds-radius-8"]
  },
  {
    name: "Divider",
    slug: "divider",
    category: "layout",
    priority: "P1",
    status: "ready",
    summary: "관련 group 사이의 visual separator입니다.",
    purpose: "새 container를 만들지 않고 인접 section을 구분할 때 사용합니다.",
    primitive: "hr or role='separator'",
    apg: "",
    props: ["orientation", "decorative"],
    states: ["horizontal", "vertical"],
    tokens: ["--ds-color-border-default"]
  },
  {
    name: "Table",
    slug: "table",
    category: "data-display",
    priority: "P1",
    status: "ready",
    summary: "비교 가능한 record를 row와 column으로 구조화합니다.",
    purpose: "scanning, sorting, column alignment가 중요한 dense data에 사용합니다.",
    primitive: "table",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/table/",
    props: ["columns", "rows", "density", "sortable", "selectionMode", "striped", "hoverable", "stickyHeader", "emptyMessage", "rowKey", "rowActions", "sortState", "defaultSortState", "selectedRowKeys", "defaultSelectedRowKeys", "renderCell", "onSortChange", "onSelectedRowKeysChange"],
    states: ["default", "hover", "sorted", "selected", "empty", "loading"],
    tokens: ["--ds-color-border-default", "--ds-color-bg-surface", "--ds-color-bg-muted"]
  },
  {
    name: "DataGrid",
    slug: "data-grid",
    category: "data-display",
    priority: "P1",
    status: "ready",
    summary: "sorting, selection, row action, keyboard row navigation, column resize를 포함한 interactive tabular grid입니다.",
    purpose: "static table보다 풍부한 control이 필요한 dense record를 구조적으로 탐색할 때 사용합니다.",
    primitive: "table with grid-like interactions",
    apg: "https://www.w3.org/WAI/ARIA/apg/patterns/grid/",
    props: ["caption", "columns", "rows", "density", "sortable", "selectionMode", "striped", "stickyHeader", "loading", "emptyMessage", "rowKey", "rowActions", "sortState", "defaultSortState", "selectedRowKeys", "defaultSelectedRowKeys", "activeRowKey", "defaultActiveRowKey", "keyboardNavigation", "resizableColumns", "onSort", "onSortChange", "onSelectedRowKeysChange", "onSelectionChange", "onActiveRowKeyChange", "onColumnResize"],
    states: ["default", "hover", "sorted", "selected", "active", "empty", "loading", "resizing"],
    tokens: ["--ds-color-border-default", "--ds-color-bg-surface", "--ds-color-bg-muted"]
  },
  {
    name: "EmptyState",
    slug: "empty-state",
    category: "data-display",
    priority: "P1",
    status: "ready",
    summary: "view에 data가 없을 때 보여주는 guidance입니다.",
    purpose: "content가 없는 이유를 설명하고 다음으로 유용한 action을 제안할 때 사용합니다.",
    primitive: "section",
    apg: "",
    props: ["title", "description", "icon", "actions", "tone"],
    states: ["no-data", "filtered", "error", "permission"],
    tokens: ["--ds-color-text-muted", "--ds-color-bg-surface", "--ds-radius-8"]
  },
  {
    name: "List",
    slug: "list",
    category: "data-display",
    priority: "P1",
    status: "ready",
    summary: "동질적인 item을 세로로 보여주는 collection입니다.",
    purpose: "activity, option, navigation-adjacent record, compact summary에 사용합니다.",
    primitive: "ul or ol",
    apg: "",
    props: ["items", "density", "dividers", "selectionMode", "variant", "renderItem", "leading", "trailing", "disabled", "selected"],
    states: ["default", "hover", "selected", "disabled", "empty", "loading"],
    tokens: ["--ds-color-border-default", "--ds-color-bg-surface", "--ds-space-4"]
  }
];
